package main

import (
	"encoding/json"
	"net/http"
	"os"
	"time"

	"github.com/google/uuid"
	auth "github.com/thulio63/chirpy/internal/auth"
	"github.com/thulio63/chirpy/internal/database"
)

type User struct {
	ID uuid.UUID `json:"id"`
	Created_At time.Time `json:"created_at"`
	Updated_At time.Time `json:"updated_at"`
	Email string `json:"email"`
	Token string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Chirpy_Red bool `json:"is_chirpy_red"`
}

func (cfg *apiConfig) handlerUserCreate(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Email string `json:"email"`
		Password string `json:"password"`
	}  
	type response struct {
		User
	}


	//prepare space for incoming data
	newUser := parameters{}
	//decode json data
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&newUser)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}
	
	//create hashed password to store
	hash, err := auth.HashPassword(newUser.Password)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't encrypt password", err)
		return
	}

	//utilizes the query from users.sql, gets variables from returned values
	//the CreateUser function was generated by sqlc
	user, err := cfg.db.CreateUser(r.Context(), database.CreateUserParams{
		Email: newUser.Email,
		HashedPassword: hash,
	})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create user", err)
		return
	}

	respondWithJSON(w, http.StatusCreated, response{
		User: User{
			ID: user.ID,
			Created_At: user.CreatedAt,
			Updated_At: user.UpdatedAt,
			Email: user.Email,
			Chirpy_Red: user.IsChirpyRed.Bool,
		},
	})
}

func (cfg *apiConfig) handlerUserUpdate(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Email string `json:"email"`
		Password string `json:"password"`
	}  
	type response struct {
		Email string `json:"email"`
	}

	//prepare space for incoming data
	userLogin := parameters{}
	//decode json data
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&userLogin)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	tok, err := auth.GetBearerToken(r.Header)
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Invalid token provided", err)
		return 
	}

	uid, err := auth.ValidateJWT(tok, os.Getenv("SECRET"))
	if err != nil {
		respondWithError(w, http.StatusUnauthorized, "Token could not be validated", err)
	}

	hashed, err := auth.HashPassword(userLogin.Password)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Failed to hash password", err)
		return 
	}

	err = cfg.db.UpdateUser(r.Context(), database.UpdateUserParams{
		Email: userLogin.Email,
		HashedPassword: hashed,
		ID: uid,
	})
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Failed to update user", err)
		return 
	}

	respondWithJSON(w, http.StatusOK, response{
		Email: userLogin.Email,
	})
}