package main

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID uuid.UUID `json:"id"`
	Created_At time.Time `json:"created_at"`
	Updated_At time.Time `json:"updated_at"`
	Email string `json:"email"`
}

func (cfg *apiConfig) handlerUserCreate(w http.ResponseWriter, r *http.Request) {
	type parameters struct {
		Email string `json:"email"`
	}  
	type response struct {
		User
	}


	//prepare space for incoming data
	newUser := parameters{}
	//decode json data
	decoder := json.NewDecoder(r.Body)
	err := decoder.Decode(&newUser)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't decode parameters", err)
		return
	}

	//utilizes the query from users.sql, gets variables from returned values
	//the CreateUser function was generated by sqlc
	user, err := cfg.db.CreateUser(r.Context(), newUser.Email)
	if err != nil {
		respondWithError(w, http.StatusInternalServerError, "Couldn't create user", err)
		return
	}

	respondWithJSON(w, http.StatusCreated, response{
		User: User{
			ID: user.ID,
			Created_At: user.CreatedAt,
			Updated_At: user.UpdatedAt,
			Email: user.Email,
		},
	})
}